services:
  api:
    image: ghcr.io/saleor/saleor:3.20
    container_name: ir-backend
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    depends_on:
      - db
      - redis
      - jaeger
    volumes:
      # shared volume between worker and api for media
      - saleor-media:/app/media
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - DASHBOARD_URL=http://localhost:9000/
      - ALLOWED_HOSTS=localhost,api
      - HTTP_IP_FILTER_ENABLED=True
      - HTTP_IP_FILTER_ALLOW_LOOPBACK_IPS=True
      - DEFAULT_CHANNEL_SLUG=ca
      - CELERY_BROKER_URL=redis://redis:6379/1
      - DATABASE_URL=postgres://saleor:saleor@db/saleor
      - DEFAULT_FROM_EMAIL=noreply@example.com
      - EMAIL_URL=smtp://mailpit:1025
      - SECRET_KEY=changeme

  dashboard:
    image: ghcr.io/saleor/saleor-dashboard:latest
    container_name: ir-dashboard
    ports:
      - 9000:80
    restart: unless-stopped

  db:
    image: docker.io/library/postgres:15-alpine
    container_name: ir-db
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-db:/var/lib/postgresql/data
      - ./replica_user.sql:/docker-entrypoint-initdb.d/replica_user.sql
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor

  redis:
    image: docker.io/library/redis:7.0-alpine
    container_name: ir-redis
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-redis:/data

  worker:
    image: ghcr.io/saleor/saleor:3.20
    container_name: ir-worker
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -B
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    depends_on:
      - redis
      - mailpit
    volumes:
      # shared volume between worker and api for media
      - saleor-media:/app/media
    environment:
      - HTTP_IP_FILTER_ENABLED=True
      - HTTP_IP_FILTER_ALLOW_LOOPBACK_IPS=True
      - DEFAULT_CHANNEL_SLUG=ca
      - CELERY_BROKER_URL=redis://redis:6379/1
      - DATABASE_URL=postgres://saleor:saleor@db/saleor
      - DEFAULT_FROM_EMAIL=noreply@example.com
      - EMAIL_URL=smtp://mailpit:1025
      - SECRET_KEY=changeme

  jaeger:
    image: jaegertracing/all-in-one
    container_name: ir-jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - type: tmpfs
        target: /tmp

  mailpit:
    image: axllent/mailpit
    container_name: ir-mailpit
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui. Visit http://localhost:8025/ to check emails
    restart: unless-stopped
    networks:
      - saleor-backend-tier

volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local
  saleor-media:

networks:
  saleor-backend-tier:
    driver: bridge
    name: saleor-backend-tier
